### ISSUE TITLE
Microsoft.AspNetCore.Identity.EntityFrameworkCore seems to be missing from the package

### ISSUE THREAD

**Issue by jeffward01** [madeyoga/AuthEndpoints#90]
Hello!

GREAT library!

I am just running your demo app with the instructions here: [Quick Start](https://madeyoga.github.io/AuthEndpoints/wiki/get-started.html)

I see here that `.AddEntityFrameworkStores<MyDbContext>()` is required:

![image](https://user-images.githubusercontent.com/12589359/184279067-e3cb8fbd-2726-44bc-a79f-da1fd3a3ed22.png)

The reference of   `.AddEntityFrameworkStores` is 'not found' until you install the nuget package: `Microsoft.AspNetCore.Identity.EntityFrameworkCore`

I am not sure if this is a bug, or if the user is required to install `Microsoft.AspNetCore.Identity.EntityFrameworkCore` themselves.  I just wanted to report this.

Thanks!

**Comment by madeyoga** [comment]
Hi Jeff Ward, thank you for the positive feedback!

Yes, that is correct. AuthEndpoints does not ship with `Microsoft.AspNetCore.Identity.EntityFrameworkCore` package;
consequently, the user is required to install the package themselves. 

Thanks for the report! I'll update the documentation accordingly.

Also, I'm thinking about adding those identity services to the `AddAuthEndpointsCore` and `AddRefreshTokenStore()`. This will improve usability for sure. However, I'm not sure if this is good or not.

**Comment by madeyoga** [comment]
f2e7901b74e7fcefb0cc92fc829b3b0c10e407c4
